server:
  port: ${paascloud.server.provider.uac.port:8000}
  tomcat:
    uri-encoding: UTF-8
    remote-ip-header: x-forwarded-for
  use-forward-headers: true
spring:
  application:
    name: @pom.artifactId@
  profiles:
    active: @profileActive@
  boot:
    admin:
      username: ${security.user.name:admin}
      password: ${security.user.password:admin}
  redis:
    host: ${spring.redis.host:paascloud-db-redis}
    password: ${spring.redis.password:123456}
    port: ${spring.redis.port:6379}
    timeout: ${spring.redis.timeout:0}
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://paascloud-db-mysql:3306/paascloud_uac?characterEncoding=utf8&useSSL=false
    username: ${spring.datasource.username:root}
    password: ${spring.datasource.password:123456}
    filters: stat,wall
    druid:
      initial-size: 10
      min-idle: 10
      max-active: 30
      test-on-borrow: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      web-stat-filter:
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
      stat-view-servlet:
        allow:
        login-username: admin
        login-password: admin
  zipkin:
    base-url: http://paascloud-zipkin:8020
  sleuth:
    sampler:
      percentage: 1.0
info:
  owner: paascloud.net@gmail.com
  version: @project.version@
paascloud:
  enableSqlLogInterceptor: false
  aliyun:
    key:
      accessKeyId: yourAliyunAccessKey
      accessKeySecret: yourAliyunKeySecret
    rocketMq:
      enable: true
      reliableMessageConsumer: false
      reliableMessageProducer: true
      namesrvAddr: paascloud-mq-rocket:9876
      instanceName: paascloud-provider-uac
      consumerGroup: CID_UAC
      producerGroup: PID_UAC
    sms:
      signName:
      regionId: cn-beijing
      endpoint:
      endpointName: cn-beijing
      product: Dysmsapi
      domain: dysmsapi.aliyuncs.com
  auth:
    rest-pwd-url: http://dev-login.paascloud.net/resetPwd?resetPwdKey=
    active-user-url: http://dev-api.paascloud.net:7979/uac/auth/activeUser/
    refresh-token-url: http://dev-api.paascloud.net:7979/uac/oauth/token
  token:
    interceptor:
      enable: true
  zk:
    zkAddressList: paascloud-provider-zk:2181
  swagger:
    title: @pom.artifactId@
    description: @pom.description@
  oauth2:
    jwtSigningKey: paascloud
    client:
      id: ${security.oauth2.resource.id}
      accessTokenUrl: ${security.oauth2.client.access-token-uri}
      clientId: ${security.oauth2.client.clientId}
      clientSecret: ${security.oauth2.client.clientSecret}
      clientAuthenticationScheme: header
  security:
    social:
      filterProcessesUrl: /uac/auth/callback
      qq:
        app-id: 101431061
        app-secret: 0154c848f45fc705412462d4f99a592c
        providerId: qq
      weixin:
        app-id: wxd99431bbff8305a0
        app-secret: 60f78681d063590a469f1b297feff3c4
        providerId: weixin
    code:
      image:
        expireIn: 180
        url: /uac/auth/register,/uac/auth/submitResetPwdEmail,/uac/auth/code/sms
      sms:
        expireIn: 600
        url: /uac/auth/submitResetPwdPhone
        mobileMaxSendCount: 1
        ipMaxSendCount: 2
        totalMaxSendCount: 3
    oauth2:
      tokenStore: jwt
      clients[0]:
        clientId: paascloud-client-uac
        clientSecret: paascloudClientSecret
        accessTokenValidateSeconds: 7200
        scope: "*"
      clients[1]:
        clientId: paascloud-browser
        clientSecret: paascloudClientSecret
        accessTokenValidateSeconds: 7200
        scope: "*"
      clients[2]:
        clientId: paascloud-client-gateway
        clientSecret: paascloudClientSecret
        accessTokenValidateSeconds: 7200
        scope: "*"
      clients[3]:
        clientId: paascloud-client-zipkin
        clientSecret: paascloudClientSecret
        accessTokenValidateSeconds: 7200
        scope: "*"
      clients[4]:
        clientId: paascloud-client-mdc
        clientSecret: paascloudClientSecret
        accessTokenValidateSeconds: 7200
        scope: "*"
      clients[5]:
        clientId: paascloud-client-omc
        clientSecret: paascloudClientSecret
        accessTokenValidateSeconds: 7200
        scope: "*"
      clients[6]:
        clientId: paascloud-client-opc
        clientSecret: paascloudClientSecret
        accessTokenValidateSeconds: 7200
        scope: "*"
      clients[7]:
        clientId: paascloud-client-tpc
        clientSecret: paascloudClientSecret
        accessTokenValidateSeconds: 7200
        scope: "*"